### ISSUE TITLE
Installing Javascript feather dependencies

### ISSUE THREAD

**Issue by jgarte** [Vechro/mint-feather#1]
Hi, I first wanted to say great project!

I wanted to ask, how is it that you get the [feather-icons](https://www.npmjs.com/package/feather-icons) dependency installed so that it may be used with `mint-feather`?

Any help is greatly appreciated.

**Comment by Vechro** [comment]
As you would with any other dependency in Mint, you add it to your project's mint.json as per https://www.mint-lang.com/guide/getting-started/configuration.
